export const vaccinationData = [
  {
    id: 'rabies',
    name: 'Rabies',
    type: 'Overdue',
    date: '01 Dec 2023',
    veterinar: 'Find veterinar',
  },
  {
    id: 'distemper',
    name: 'Distemper',
    type: 'Core',
    date: '15 Jan 2024',
    veterinar: 'Dr. Jane Smith',
  },
  {
    id: 'lyme-disease',
    name: 'Lyme disease',
    type: 'Noncore',
    date: '25 Jun 2024',
    veterinar: 'Dr. Jennifer Green',
  },
  {
    id: 'parvo',
    name: 'Parvovirus',
    type: 'Core',
    date: '20 Feb 2024',
    veterinar: 'Dr. James Wilson',
  },
  {
    id: 'adenovirus',
    name: 'Adenovirus',
    type: 'Core',
    date: '10 Mar 2024',
    veterinar: 'Dr. Sarah Taylor',
  },
  {
    id: 'leptospirosis',
    name: 'Leptospirosis',
    type: 'Noncore',
    date: '05 Apr 2024',
    veterinar: 'Dr. Emily Davis',
  },
  {
    id: 'bordetella',
    name: 'Bordetella',
    type: 'Noncore',
    date: '18 May 2024',
    veterinar: 'Dr. Michael Brown',
  },
  {
    id: 'canine-influenza',
    name: 'Canine Influenza',
    type: 'Overdue',
    date: '30 Jun 2023',
    veterinar: 'Find veterinar',
  },
  {
    id: 'parainfluenza',
    name: 'Parainfluenza',
    type: 'Core',
    date: '12 Jul 2024',
    veterinar: 'Dr. William Harris',
  },
  {
    id: 'corona-virus',
    name: 'Corona Virus',
    type: 'Noncore',
    date: '22 Aug 2024',
    veterinar: 'Dr. Olivia Martinez',
  },
  {
    id: 'rabies-booster',
    name: 'Rabies Booster',
    type: 'Core',
    date: '10 Nov 2024',
    veterinar: 'Dr. John Doe',
  },
]
